// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CoreAuthFooter: typeof import('./../components/core/auth/footer.vue')['default']
    CoreAuthLogin: typeof import('./../components/core/auth/login.vue')['default']
    CoreAuthPassword: typeof import('./../components/core/auth/password.vue')['default']
    CoreAuthRegister: typeof import('./../components/core/auth/register.vue')['default']
    CoreEditorMarkdown: typeof import('./../components/core/editor/markdown.vue')['default']
    CoreEditorWangEditor: typeof import('./../components/core/editor/wangEditor.vue')['default']
    CoreFormButtonComponent: typeof import('./../components/core/form/buttonComponent.vue')['default']
    CoreFormError: typeof import('./../components/core/form/error.vue')['default']
    CoreFormFieldList: typeof import('./../components/core/form/fieldList.vue')['default']
    CoreFormInputComponent: typeof import('./../components/core/form/inputComponent.vue')['default']
    CoreFormVeeValidateError: typeof import('./../components/core/form/veeValidateError.vue')['default']
    CoreHdAnimateList: typeof import('./../components/core/hd/animateList.vue')['default']
    CoreHdBreadcrumb: typeof import('./../components/core/hd/breadcrumb.vue')['default']
    CoreHdCaptcha: typeof import('./../components/core/hd/captcha.vue')['default']
    CoreHdFullscreen: typeof import('./../components/core/hd/fullscreen.vue')['default']
    CoreHdTab: typeof import('./../components/core/hd/tab.vue')['default']
    CoreHdTableComponent: typeof import('./../components/core/hd/tableComponent.vue')['default']
    CoreHdValidateCode: typeof import('./../components/core/hd/validateCode.vue')['default']
    CoreModuleSelectModule: typeof import('./../components/core/module/selectModule.vue')['default']
    CoreSiteItem: typeof import('./../components/core/site/item.vue')['default']
    CoreSitePermission: typeof import('./../components/core/site/permission.vue')['default']
    CoreUploadSingleImage: typeof import('./../components/core/upload/singleImage.vue')['default']
    CoreUserDrop: typeof import('./../components/core/user/drop.vue')['default']
    CoreUserInfo: typeof import('./../components/core/user/info.vue')['default']
    CoreUserNotification: typeof import('./../components/core/user/notification.vue')['default']
    CoreUserSelectUser: typeof import('./../components/core/user/selectUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
