// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EditorMarkdown: typeof import('./../src/components/editor/markdown.vue')['default']
    EditorWangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
    FormButton: typeof import('./../src/components/form/button.vue')['default']
    FormError: typeof import('./../src/components/form/error.vue')['default']
    FormInput: typeof import('./../src/components/form/input.vue')['default']
    FormVeeValidateError: typeof import('./../src/components/form/veeValidateError.vue')['default']
    HdAnimateList: typeof import('./../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../src/components/hd/breadcrumb.vue')['default']
    HdCaptcha: typeof import('./../src/components/hd/captcha.vue')['default']
    HdCode: typeof import('./../src/components/hd/code.vue')['default']
    HdNotification: typeof import('./../src/components/hd/notification.vue')['default']
  }
}

export { }
